# Generated by Django 5.2.10 on 2026-01-22 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GithubUser",
            fields=[
                (
                    "username",
                    models.CharField(
                        help_text="GitHub 사용자 ID (소문자 정규화 권장)",
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "last_analyzed_at",
                    models.DateTimeField(blank=True, help_text="가장 최근 분석이 완료된 시각", null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="최초 생성 시각")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="마지막 정보 갱신 시각")),
            ],
        ),
        migrations.CreateModel(
            name="GithubEvent",
            fields=[
                (
                    "event_id",
                    models.CharField(
                        help_text="GitHub에서 부여한 고유 이벤트 ID",
                        max_length=50,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("event_type", models.CharField(help_text="이벤트 유형 (PushEvent, IssuesEvent 등)", max_length=100)),
                ("repo_name", models.CharField(help_text="저장소 이름 (user/repo)", max_length=255)),
                ("message", models.TextField(help_text="분석 대상 텍스트 (커밋 메시지 등)")),
                ("created_at", models.DateTimeField(help_text="이벤트 실제 발생 시각 (GitHub 시간)")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="이벤트 발생 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="card.githubuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("persona_title", models.CharField(help_text="LLM이 생성한 페르소나 제목", max_length=100)),
                ("comment", models.TextField(help_text="LLM이 생성한 한 줄 요약")),
                (
                    "status_enum",
                    models.CharField(
                        choices=[
                            ("JOY", "기쁨"),
                            ("ANGER", "분노"),
                            ("ANXIETY", "불안"),
                            ("SADNESS", "슬픔"),
                            ("CONFUSION", "혼란"),
                            ("NEUTRAL", "중립"),
                            ("IDLE", "대기/없음"),
                        ],
                        help_text="감정 상태",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(blank=True, help_text="LLM이 분석한 근거", null=True)),
                (
                    "analysis_metadata",
                    models.JSONField(default=dict, help_text="사용된 모델, 분석된 이벤트 수 등 메타데이터"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="결과 생성 시각")),
                (
                    "user",
                    models.ForeignKey(
                        help_text="분석 대상 사용자",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="card.githubuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
